export const mockUsers = [
  {
    name: 'Wilmer Wright_1',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame1.png',
    id: 1,
  },
  {
    name: 'Wilmer Wright_2',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame2.png',
    id: 2,
  },
  {
    name: 'Wilmer Wright_3',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame3.png',
    id: 3,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame4.png',
    id: 4,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame5.png',
    id: 5,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame6.png',
    id: 6,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame7.png',
    id: 7,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame8.png',
    id: 8,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame9.png',
    id: 9,
  },
  {
    name: 'Wilmer Wright',
    email: 'wilWright@mail.com',
    band: 'Artist/Band member, Manager/Label',
    img: '/assets/mockImg/frame10.png',
    id: 10,
  },
];
