import musicTracks from './musicTracks';

export const mockReleases = [
  {
    title: 'Title_1',
    band: 'Artist/Band_1',
    id: 1,
    img: '/assets/mockImg/rectangle_0.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_2',
    band: 'Artist/Band_2',
    id: 2,
    img: '/assets/mockImg/rectangle_1.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_3',
    band: 'Artist/Band_3',
    id: 3,
    img: '/assets/mockImg/rectangle_2.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_4',
    band: 'Artist/Band_4',
    id: 4,
    img: '/assets/mockImg/rectangle_3.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_5',
    band: 'Artist/Band_5',
    id: 5,
    img: '/assets/mockImg/rectangle_4.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_6',
    band: 'Artist/Band_6',
    id: 6,
    img: '/assets/mockImg/rectangle_5.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_7',
    band: 'Artist/Band_7',
    id: 7,
    img: '/assets/mockImg/rectangle_0.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_8',
    band: 'Artist/Band_8',
    id: 8,
    img: '/assets/mockImg/rectangle_1.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_9',
    band: 'Artist/Band_9',
    id: 9,
    img: '/assets/mockImg/rectangle_2.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_10',
    band: 'Artist/Band_10',
    id: 10,
    img: '/assets/mockImg/rectangle_3.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_11',
    band: 'Artist/Band_11',
    id: 11,
    img: '/assets/mockImg/rectangle_4.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_12',
    band: 'Artist/Band_12',
    id: 12,
    img: '/assets/mockImg/rectangle_5.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_13',
    band: 'Artist/Band_13',
    id: 13,
    img: '/assets/mockImg/rectangle_0.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_14',
    band: 'Artist/Band_14',
    id: 14,
    img: '/assets/mockImg/rectangle_1.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_15',
    band: 'Artist/Band_15',
    id: 15,
    img: '/assets/mockImg/rectangle_2.jpg',
    tracks: musicTracks,
  },
  {
    title: 'Title_16',
    band: 'Artist/Band_16',
    id: 16,
    img: '/assets/mockImg/rectangle_3.jpg',
    tracks: musicTracks,
  },
];
