const musicTracks = [
	{
		ID: '1',
		name: 'Memories',
		src: 'https://www.bensound.com/bensound-music/bensound-memories.mp3',
		url: '/assets/images/mockImg/artist_5.jpg',
		band: 'Artist/Band_1  oweruytworeiuytowuireytoiuwyertouiyweortuiy',
	},
	{
		ID: '2',
		name: 'Creative Minds',
		src: 'https://www.bensound.com/bensound-music/bensound-creativeminds.mp3',
		url: '/assets/images/mockImg/artist_4.jpg',
		band: 'Artist/Band_2',
	},
	{
		ID: '3',
		name: 'Acoustic Breeze',
		src: 'https://www.bensound.com/bensound-music/bensound-acousticbreeze.mp3',
		url: '/assets/images/mockImg/artist_3.jpg',
		band: 'Artist/Band_3',
	},
	{
		ID: '4',
		name: 'Sunny',
		src: 'https://www.bensound.com/bensound-music/bensound-sunny.mp3',
		url: '/assets/images/mockImg/artist_2.jpg',
		band: 'Artist/Band_4',
	},
	{
		ID: '5',
		name: 'Tenderness',
		src: 'https://www.bensound.com/bensound-music/bensound-tenderness.mp3',
		url: '/assets/images/mockImg/artist_1.jpg',
		band: 'Artist/Band_5',
	},
	{
		ID: '6',
		name: 'Once Again',
		src: 'https://www.bensound.com/bensound-music/bensound-onceagain.mp3',
		url: '/assets/images/mockImg/play_track_img.jpg',
		band: 'Artist/Band_6',
	},
	{
		ID: '7',
		name: 'Sweet',
		src: 'https://www.bensound.com/bensound-music/bensound-sweet.mp3',
		url: '/assets/images/mockImg/artist_5.jpg',
		band: 'Artist/Band_7',
	},
	{
		ID: '8',
		name: 'Love',
		src: 'https://www.bensound.com/bensound-music/bensound-love.mp3',
		url: '/assets/images/mockImg/artist_4.jpg',
		band: 'Artist/Band_8',
	},
	{
		ID: '9',
		name: 'Piano Moment',
		src: 'https://www.bensound.com/bensound-music/bensound-pianomoment.mp3',
		url: '/assets/images/mockImg/artist_3.jpg',
		band: 'Artist/Band_9',
	},
	{
		ID: '10',
		name: 'E.R.F',
		src: 'https://www.bensound.com/bensound-music/bensound-erf.mp3',
		url: '/assets/images/mockImg/artist_2.jpg',
		band: 'Artist/Band_10',
	},
	{
		ID: '11',
		name: 'Dreams',
		src: 'https://www.bensound.com/bensound-music/bensound-dreams.mp3',
		url: '/assets/images/mockImg/artist_1.jpg',
		band: 'Artist/Band_11',
	},
	{
		ID: '12',
		name: 'A Day To Remember',
		src: 'https://www.bensound.com/royalty-free-music/track/a-day-to-remember-wedding-music',
		url: '/assets/images/mockImg/play_track_img.jpg',
		band: 'Artist/Band_12',
	},
	{
		ID: '13',
		name: 'Adventure',
		src: 'https://www.bensound.com/bensound-music/bensound-adventure.mp3',
		url: '/assets/images/mockImg/play_track_img.jpg',
		band: 'Artist/Band_13',
	},
	{
		ID: '14',
		name: 'Photo Album',
		src: 'https://www.bensound.com/bensound-music/bensound-photoalbum.mp3',
		url: '/assets/images/mockImg/artist_5.jpg',
		band: 'Artist/Band_14',
	},
	{
		ID: '15',
		name: 'November',
		src: 'https://www.bensound.com/bensound-music/bensound-november.mp3',
		url: '/assets/images/mockImg/artist_2.jpg',
		band: 'Artist/Band_15',
	},
];

export default musicTracks;
